# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(1, '50ml'), (2, '100ml'), (3, '200ml')])),
            ],
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nazwa')),
                ('country', models.CharField(max_length=64, verbose_name='kraj')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cena')),
                ('capacity', models.IntegerField(choices=[(1, '200ml'), (2, '500ml'), (3, '700ml'), (4, '750ml'), (5, '1000ml')], verbose_name='pojemnosc')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='spirit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Spirit', verbose_name='przedmiot'),
        ),
    ]
