# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171017_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slainteed',
            new_name='Slainteet',
        ),
    ]
