# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20171017_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_quantity', models.FloatField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Order')),
                ('spirit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderprocess',
            name='spirit_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.SpiritCart'),
        ),
    ]
