# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20171018_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spiritavailability',
            old_name='product',
            new_name='spirit',
        ),
    ]
