# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(choices=[(1, 50), (2, 100), (3, 200)]),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spirit',
            name='capacity',
            field=models.IntegerField(choices=[(1, 200), (2, 500), (3, 700), (4, 750), (5, 1000)], verbose_name='pojemnosc'),
        ),
    ]
