# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20171018_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprocess',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderprocess',
            name='spirit',
        ),
        migrations.RemoveField(
            model_name='orderprocess',
            name='spirit_cart',
        ),
        migrations.RemoveField(
            model_name='spiritavailability',
            name='spirit',
        ),
        migrations.RemoveField(
            model_name='spiritcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderProcess',
        ),
        migrations.DeleteModel(
            name='SpiritAvailability',
        ),
        migrations.DeleteModel(
            name='SpiritCart',
        ),
    ]
