# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20171018_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=60)),
                ('slainteet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Slainteet')),
            ],
        ),
    ]
